# Generated by Django 2.1.1 on 2018-09-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='lote',
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
    ]
