# Generated by Django 2.1.1 on 2018-09-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelote',
            name='fotos',
            field=models.FilePathField(allow_files=False, allow_folders=True, match='lot.*', path='/Users/sebastiangiraldo/roya_cafe/coffee_rescuer/data', recursive=True, unique=True),
        ),
        migrations.AlterField(
            model_name='detallelote',
            name='info_sensores',
            field=models.FilePathField(match='.*.json$', path='/Users/sebastiangiraldo/roya_cafe/coffee_rescuer/data', recursive=True, unique=True),
        ),
    ]
