# Generated by Django 2.1.1 on 2018-09-16 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_hongo', models.PositiveIntegerField(choices=[(0, 'Etapa 0'), (1, 'Etapa 1'), (2, 'Etapa 2'), (3, 'Etapa 3')], default=0)),
                ('info_sensores', models.FilePathField()),
                ('fotos', models.FilePathField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lote',
            name='etapa_hongo',
        ),
        migrations.AlterField(
            model_name='lote',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detallelote',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lote.Lote'),
        ),
    ]
