# Generated by Django 2.1.1 on 2018-09-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0002_auto_20180916_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelote',
            name='info_sensores',
            field=models.FilePathField(allow_folders=True, recursive=True, verbose_name='C:\\Users\\user\\Documents\\pythonProjects\\roya_cafe\\coffee_rescuer\\data'),
        ),
    ]
