# Generated by Django 2.1.1 on 2018-09-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0003_auto_20180916_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelote',
            name='info_sensores',
            field=models.FilePathField(allow_folders=True, recursive=True, verbose_name='E:\\Imagenes'),
        ),
    ]
