# Generated by Django 2.1.1 on 2018-09-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0004_auto_20180916_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelote',
            name='fotos',
            field=models.FilePathField(allow_folders=True, path='C:\\Users\\user\\Documents\\pythonProjects\\roya_cafe\\coffee_rescuer\\data', recursive=True),
        ),
        migrations.AlterField(
            model_name='detallelote',
            name='info_sensores',
            field=models.FilePathField(match='*.json', path='C:\\Users\\user\\Documents\\pythonProjects\\roya_cafe\\coffee_rescuer\\data', recursive=True),
        ),
    ]
