# Generated by Django 2.1.1 on 2018-09-16 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo_coordenadas', models.FileField(default='C:\\Users\\user\\Documents\\pythonProjects\\roya_cafe\\coffee_rescuer', upload_to='C:\\Users\\user\\Documents\\pythonProjects\\roya_cafe\\coffee_rescuer\\data\\<function Finca.finca_directory_path at 0x0479BB28>')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
