# Generated by Django 2.1.1 on 2018-09-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='archivo_coordenadas',
            field=models.FilePathField(match='coordenadas.json', path='/Users/sebastiangiraldo/roya_cafe/coffee_rescuer/data', recursive=True, unique=True),
        ),
    ]
